version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.example.com
    volumes:
      - $PWD/srv/config:/etc/gitlab
      - $PWD/srv/logs:/var/log/gitlab
      - $PWD/srv/data:/var/opt/gitlab
    ports:
      - "443:443"
      - "80:80"
      - "2022:22"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/srv/gitlab-runner/:/etc/gitlab-runner
    links:
     - gitlab:gitlab.example.com
    ports:
      - "8080:8080"

  web:
    build: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/oauth2_proxy.cfg:/etc/oauth2_proxy.cfg:ro
      - ./nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./nginx:/nginx
    links:
     - gitlab:gitlab.example.com
    ports:
      - "8081:8081"


